/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.vass.ficha.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

/**
 * The base model interface for the tipoServicio service. Represents a row in the &quot;FICHA_tipoServicio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link es.vass.ficha.model.impl.tipoServicioModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link es.vass.ficha.model.impl.tipoServicioImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tipoServicio
 * @see es.vass.ficha.model.impl.tipoServicioImpl
 * @see es.vass.ficha.model.impl.tipoServicioModelImpl
 * @generated
 */
@ProviderType
public interface tipoServicioModel extends BaseModel<tipoServicio> {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a tipo servicio model instance should use the {@link tipoServicio} interface instead.
	 */

	/**
	 * Returns the primary key of this tipo servicio.
	 *
	 * @return the primary key of this tipo servicio
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this tipo servicio.
	 *
	 * @param primaryKey the primary key of this tipo servicio
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the id tipo servicio of this tipo servicio.
	 *
	 * @return the id tipo servicio of this tipo servicio
	 */
	public long getIdTipoServicio();

	/**
	 * Sets the id tipo servicio of this tipo servicio.
	 *
	 * @param idTipoServicio the id tipo servicio of this tipo servicio
	 */
	public void setIdTipoServicio(long idTipoServicio);

	/**
	 * Returns the nombre tipo servicio of this tipo servicio.
	 *
	 * @return the nombre tipo servicio of this tipo servicio
	 */
	@AutoEscape
	public String getNombreTipoServicio();

	/**
	 * Sets the nombre tipo servicio of this tipo servicio.
	 *
	 * @param nombreTipoServicio the nombre tipo servicio of this tipo servicio
	 */
	public void setNombreTipoServicio(String nombreTipoServicio);

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(es.vass.ficha.model.tipoServicio tipoServicio);

	@Override
	public int hashCode();

	@Override
	public CacheModel<es.vass.ficha.model.tipoServicio> toCacheModel();

	@Override
	public es.vass.ficha.model.tipoServicio toEscapedModel();

	@Override
	public es.vass.ficha.model.tipoServicio toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}