/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package es.vass.ficha.model.impl;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;

import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.portal.kernel.util.StringBundler;

import es.vass.ficha.model.tipoServicio;
import es.vass.ficha.model.tipoServicioModel;

import java.io.Serializable;

import java.sql.Types;

import java.util.HashMap;
import java.util.Map;

/**
 * The base model implementation for the tipoServicio service. Represents a row in the &quot;FICHA_tipoServicio&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface {@link tipoServicioModel} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link tipoServicioImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see tipoServicioImpl
 * @see tipoServicio
 * @see tipoServicioModel
 * @generated
 */
@ProviderType
public class tipoServicioModelImpl extends BaseModelImpl<tipoServicio>
	implements tipoServicioModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a tipo servicio model instance should use the {@link tipoServicio} interface instead.
	 */
	public static final String TABLE_NAME = "FICHA_tipoServicio";
	public static final Object[][] TABLE_COLUMNS = {
			{ "idTipoServicio", Types.BIGINT },
			{ "nombreTipoServicio", Types.VARCHAR }
		};
	public static final Map<String, Integer> TABLE_COLUMNS_MAP = new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("idTipoServicio", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("nombreTipoServicio", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE = "create table FICHA_tipoServicio (idTipoServicio LONG not null primary key,nombreTipoServicio VARCHAR(75) null)";
	public static final String TABLE_SQL_DROP = "drop table FICHA_tipoServicio";
	public static final String ORDER_BY_JPQL = " ORDER BY tipoServicio.idTipoServicio ASC";
	public static final String ORDER_BY_SQL = " ORDER BY FICHA_tipoServicio.idTipoServicio ASC";
	public static final String DATA_SOURCE = "liferayDataSource";
	public static final String SESSION_FACTORY = "liferaySessionFactory";
	public static final String TX_MANAGER = "liferayTransactionManager";
	public static final boolean ENTITY_CACHE_ENABLED = GetterUtil.getBoolean(es.vass.ficha.service.util.ServiceProps.get(
				"value.object.entity.cache.enabled.es.vass.ficha.model.tipoServicio"),
			true);
	public static final boolean FINDER_CACHE_ENABLED = GetterUtil.getBoolean(es.vass.ficha.service.util.ServiceProps.get(
				"value.object.finder.cache.enabled.es.vass.ficha.model.tipoServicio"),
			true);
	public static final boolean COLUMN_BITMASK_ENABLED = false;
	public static final long LOCK_EXPIRATION_TIME = GetterUtil.getLong(es.vass.ficha.service.util.ServiceProps.get(
				"lock.expiration.time.es.vass.ficha.model.tipoServicio"));

	public tipoServicioModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _idTipoServicio;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setIdTipoServicio(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _idTipoServicio;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return tipoServicio.class;
	}

	@Override
	public String getModelClassName() {
		return tipoServicio.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		attributes.put("idTipoServicio", getIdTipoServicio());
		attributes.put("nombreTipoServicio", getNombreTipoServicio());

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Long idTipoServicio = (Long)attributes.get("idTipoServicio");

		if (idTipoServicio != null) {
			setIdTipoServicio(idTipoServicio);
		}

		String nombreTipoServicio = (String)attributes.get("nombreTipoServicio");

		if (nombreTipoServicio != null) {
			setNombreTipoServicio(nombreTipoServicio);
		}
	}

	@Override
	public long getIdTipoServicio() {
		return _idTipoServicio;
	}

	@Override
	public void setIdTipoServicio(long idTipoServicio) {
		_idTipoServicio = idTipoServicio;
	}

	@Override
	public String getNombreTipoServicio() {
		if (_nombreTipoServicio == null) {
			return "";
		}
		else {
			return _nombreTipoServicio;
		}
	}

	@Override
	public void setNombreTipoServicio(String nombreTipoServicio) {
		_nombreTipoServicio = nombreTipoServicio;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(0,
			tipoServicio.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public tipoServicio toEscapedModel() {
		if (_escapedModel == null) {
			_escapedModel = (tipoServicio)ProxyUtil.newProxyInstance(_classLoader,
					_escapedModelInterfaces, new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		tipoServicioImpl tipoServicioImpl = new tipoServicioImpl();

		tipoServicioImpl.setIdTipoServicio(getIdTipoServicio());
		tipoServicioImpl.setNombreTipoServicio(getNombreTipoServicio());

		tipoServicioImpl.resetOriginalValues();

		return tipoServicioImpl;
	}

	@Override
	public int compareTo(tipoServicio tipoServicio) {
		long primaryKey = tipoServicio.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof tipoServicio)) {
			return false;
		}

		tipoServicio tipoServicio = (tipoServicio)obj;

		long primaryKey = tipoServicio.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return ENTITY_CACHE_ENABLED;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return FINDER_CACHE_ENABLED;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<tipoServicio> toCacheModel() {
		tipoServicioCacheModel tipoServicioCacheModel = new tipoServicioCacheModel();

		tipoServicioCacheModel.idTipoServicio = getIdTipoServicio();

		tipoServicioCacheModel.nombreTipoServicio = getNombreTipoServicio();

		String nombreTipoServicio = tipoServicioCacheModel.nombreTipoServicio;

		if ((nombreTipoServicio != null) && (nombreTipoServicio.length() == 0)) {
			tipoServicioCacheModel.nombreTipoServicio = null;
		}

		return tipoServicioCacheModel;
	}

	@Override
	public String toString() {
		StringBundler sb = new StringBundler(5);

		sb.append("{idTipoServicio=");
		sb.append(getIdTipoServicio());
		sb.append(", nombreTipoServicio=");
		sb.append(getNombreTipoServicio());
		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		StringBundler sb = new StringBundler(10);

		sb.append("<model><model-name>");
		sb.append("es.vass.ficha.model.tipoServicio");
		sb.append("</model-name>");

		sb.append(
			"<column><column-name>idTipoServicio</column-name><column-value><![CDATA[");
		sb.append(getIdTipoServicio());
		sb.append("]]></column-value></column>");
		sb.append(
			"<column><column-name>nombreTipoServicio</column-name><column-value><![CDATA[");
		sb.append(getNombreTipoServicio());
		sb.append("]]></column-value></column>");

		sb.append("</model>");

		return sb.toString();
	}

	private static final ClassLoader _classLoader = tipoServicio.class.getClassLoader();
	private static final Class<?>[] _escapedModelInterfaces = new Class[] {
			tipoServicio.class, ModelWrapper.class
		};
	private long _idTipoServicio;
	private String _nombreTipoServicio;
	private tipoServicio _escapedModel;
}